"use client";

import { Label } from "@/app/ui/shadcn/label";
import { Input } from "@/app/ui/shadcn/input";
import { Info, Lock } from "lucide-react";
import { SectionCard } from "@/app/ui/my_components/Card/SectionCard";
import { UseFormReturn } from "react-hook-form";
import { BotFormInputs } from "@/schema/botSchema";

interface Props {
  form: UseFormReturn<BotFormInputs>;
}

export function EngineSettingsSection({ form }: Props) {
  const {
    register,
    formState: { errors },
  } = form;

  return (
    <SectionCard title="External Bot Engine Settings (Optional Contact Info)">
      {/* System Generated Info Block */}
      <div
        className="rounded-lg border border-primary/50 bg-primary/10 p-4 mb-6"
      >
        <div className="mb-2 flex items-center gap-2">
          <Lock className="h-4 w-4 text-primary" />
          <p className="text-sm font-semibold text-primary">
            System-Generated Credentials
          </p>
        </div>
        <p className="text-sm text-primary-foreground/80">
          The API Key, API Secret, and Webhook URL (API URL) will be
          automatically generated by the system and shown to you after clicking
          "Create Bot."
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        {/* WebSocket URL (Optional) */}
        <div className="space-y-2">
          <Label htmlFor="websocketUrl">WebSocket URL (Optional)</Label>
          <Input
            id="websocketUrl"
            placeholder="wss://your-bot/ws"
            {...register("websocketUrl")} // <-- RHF register
          />
          {errors.websocketUrl && (
            <p className="text-sm text-red-500">
              {errors.websocketUrl.message}
            </p>
          )}
        </div>

        {/* Health Check URL (Optional) */}
        <div className="space-y-2">
          <Label htmlFor="healthUrl">Health Check URL (Optional)</Label>
          <Input
            id="healthUrl"
            placeholder="https://api.my-bot.com/health"
            {...register("healthUrl")} // <-- RHF register
          />
          {errors.healthUrl && (
            <p className="text-sm text-red-500">{errors.healthUrl.message}</p>
          )}
        </div>
      </div>

      {/* Signal Schema */}
      <div className="rounded-lg border border-border bg-muted/50 p-4 mt-6">
        <div className="mb-2 flex items-center gap-2">
          <Info className="h-4 w-4 text-primary" />
          <p className="text-sm">Required Signal Schema</p>
        </div>

        <pre className="text-xs bg-background p-3 rounded">
          {`{
  "action": "BUY" or "SELL",
  "coin_symbol": "BTC",
  "quantity": 0.001,
  "price": 65000.00,
  "signal_timestamp": 1713452345
  "auth_key": "..." // Your generated API Key
}`}
        </pre>
        <p className="text-xs text-muted-foreground mt-2">
          The external bot must POST to the generated Webhook URL with this
          schema.
        </p>
      </div>
    </SectionCard>
  );
}
