export const SYMBOLS: string[] = [
  "BTC",
  "ETH",
  "BNB",
  "SOL",
  "XRP",
  "DOGE",
  "ADA",
  "AVAX",
  "MATIC",
  "DOT",
  "LINK",
  "TON",
  "TRX",
  "SHIB",
  "BCH",
  "LTC",
  "UNI",
  "ATOM",
  "ETC",
  "XMR",
  "ALGO",
  "APT",
  "ARB",
  "OP",
  "FIL",
  "HBAR",
  "ICP",
  "INJ",
  "QNT",
  "EGLD",
  "NEAR",
  "VET",
  "AAVE",
  "MKR",
  "RUNE",
  "SUI",
  "TIA",
  "SEI",
  "FLOW",
  "GALA",
  "THETA",
  "KAVA",
  "XTZ",
  "AXS",
  "SAND",
];

export const COIN_LOGOS: Record<string, string> = {
  BTC: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
  ETH: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
  BNB: "https://assets.coingecko.com/coins/images/825/large/binance-coin-logo.png",
  SOL: "https://assets.coingecko.com/coins/images/4128/large/solana.png",
  XRP: "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png",
  DOGE: "https://assets.coingecko.com/coins/images/5/large/dogecoin.png",
  ADA: "https://assets.coingecko.com/coins/images/975/large/cardano.png",
  AVAX: "https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369",
  MATIC:
    "https://assets.coingecko.com/coins/images/4713/large/matic-token-icon.png",
  DOT: "https://assets.coingecko.com/coins/images/12171/large/polkadot.png",
  LINK: "https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png",
  TON: "https://coin-images.coingecko.com/coins/images/26652/large/ton_symbol.png",
  TRX: "https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png",
  SHIB: "https://coin-images.coingecko.com/coins/images/11939/large/shiba.png",
  BCH: "https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png",
  LTC: "https://coin-images.coingecko.com/coins/images/2/large/litecoin.png",
  UNI: "https://coin-images.coingecko.com/coins/images/12504/large/uniswap-uni.png",
  ATOM: "https://coin-images.coingecko.com/coins/images/1481/large/cosmos_hub.png",
  ETC: "https://coin-images.coingecko.com/coins/images/453/large/ethereum-classic.png",
  XMR: "https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png",
  ALGO: "https://coin-images.coingecko.com/coins/images/4380/large/Algorand.png",
  APT: "https://coin-images.coingecko.com/coins/images/26455/large/aptos_round.png",
  ARB: "https://coin-images.coingecko.com/coins/images/16547/large/arb.png",
  OP: "https://coin-images.coingecko.com/coins/images/25244/large/OP.png",
  FIL: "https://coin-images.coingecko.com/coins/images/12817/large/filecoin.png",
  HBAR: "https://coin-images.coingecko.com/coins/images/3688/large/hbar.png",
  ICP: "https://coin-images.coingecko.com/coins/images/14495/large/internet_computer.png",
  INJ: "https://coin-images.coingecko.com/coins/images/12882/large/Injective_Protocol_Logo.png",
  QNT: "https://coin-images.coingecko.com/coins/images/3373/large/quant_network.png",
  EGLD: "https://coin-images.coingecko.com/coins/images/12335/large/MultiversX.png",
  NEAR: "https://coin-images.coingecko.com/coins/images/10365/large/near.png",
  VET: "https://coin-images.coingecko.com/coins/images/1167/large/VET_Token_Logo.png",
  AAVE: "https://coin-images.coingecko.com/coins/images/12645/large/AAVE.png",
  MKR: "https://coin-images.coingecko.com/coins/images/1364/large/mkr.png",
  RUNE: "https://coin-images.coingecko.com/coins/images/6595/large/thorchain.png",
  SUI: "https://coin-images.coingecko.com/coins/images/25780/large/sui_logo.png",
  TIA: "https://coin-images.coingecko.com/coins/images/31065/large/tia.png",
  SEI: "https://coin-images.coingecko.com/coins/images/31056/large/sei.png",
  FLOW: "https://coin-images.coingecko.com/coins/images/13446/large/flow.png",
  GALA: "https://coin-images.coingecko.com/coins/images/12493/large/GALA-COIN.png",
  THETA:
    "https://coin-images.coingecko.com/coins/images/2538/large/theta_token_logo.png",
  KAVA: "https://coin-images.coingecko.com/coins/images/9761/large/KAVA.png",
  XTZ: "https://coin-images.coingecko.com/coins/images/976/large/Tezos-logo.png",
  AXS: "https://coin-images.coingecko.com/coins/images/13029/large/axie_infinity_logo.png",
  SAND: "https://coin-images.coingecko.com/coins/images/12129/large/sandbox_logo.png",
};
