import { mockCoins } from "./Coin";

export interface Bot {
  id: string;
  name: string;
  strategy: string;
  riskLevel: "Low" | "Medium" | "High";
  roi7d: number;
  roi30d: number;
  roiAllTime: number;
  roi1d: number;
  pnl1d: number;
  pnl7d: number;
  pnl30d: number;
  maxDrawdown: number;
  assets: string[];
  activeUsers: number;
  description?: string;
  winRate?: number;
  sharpeRatio?: number;
  avgDailyTrades?: number;
  status: string;
  coin: string;
}

const getRandomCoinSymbol = () => {
  if (!mockCoins || mockCoins.length === 0) return "BTC";
  return mockCoins[Math.floor(Math.random() * mockCoins.length)].symbol;
};

export const botDatabase: Bot[] = [
  {
    id: "1",
    name: "Alpha Trend Pro",
    strategy: "Trend Following",
    riskLevel: "Medium",
    roi1d: 2.8,
    roi7d: 12.5,
    roi30d: 45.3,
    roiAllTime: 234.7,
    pnl1d: 142.5,
    pnl7d: 625.8,
    pnl30d: 2265.4,
    maxDrawdown: -8.2,
    assets: ["BTC", "ETH", "BNB"],
    activeUsers: 1482,
    description:
      "Advanced trend-following AI that identifies and rides major market trends",
    winRate: 68.5,
    sharpeRatio: 2.34,
    avgDailyTrades: 4.2,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "2",
    name: "Scalper Elite",
    strategy: "Scalping",
    riskLevel: "High",
    roi1d: 1.5,
    roi7d: 8.3,
    roi30d: 38.9,
    roiAllTime: 189.4,
    pnl1d: 87.3,
    pnl7d: 498.6,
    pnl30d: 1934.5,
    maxDrawdown: -15.4,
    assets: ["BTC", "ETH", "SOL", "MATIC"],
    activeUsers: 923,
    description:
      "High-frequency trading bot optimized for quick profits in volatile markets",
    winRate: 72.3,
    sharpeRatio: 1.89,
    avgDailyTrades: 12.7,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "3",
    name: "Grid Master",
    strategy: "Grid Trading",
    riskLevel: "Low",
    roi1d: 0.8,
    roi7d: 4.2,
    roi30d: 18.6,
    roiAllTime: 98.3,
    pnl1d: 48.2,
    pnl7d: 252.1,
    pnl30d: 1116.3,
    maxDrawdown: -5.1,
    assets: ["ETH", "BNB", "ADA"],
    activeUsers: 2341,
    description:
      "Systematic grid trading strategy for consistent returns in ranging markets",
    winRate: 65.8,
    sharpeRatio: 2.87,
    avgDailyTrades: 3.5,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "4",
    name: "Mean Reversion AI",
    strategy: "Mean Reversion",
    riskLevel: "Medium",
    roi1d: 1.9,
    roi7d: 9.7,
    roi30d: 31.2,
    roiAllTime: 156.8,
    pnl1d: 105.4,
    pnl7d: 582.3,
    pnl30d: 1871.8,
    maxDrawdown: -9.8,
    assets: ["BTC", "ETH", "LINK"],
    activeUsers: 1756,
    description:
      "Statistical arbitrage bot capitalizing on price deviations from mean values",
    winRate: 70.1,
    sharpeRatio: 2.15,
    avgDailyTrades: 5.8,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "5",
    name: "DCA Optimizer",
    strategy: "DCA",
    riskLevel: "Low",
    roi1d: 0.6,
    roi7d: 3.8,
    roi30d: 15.4,
    roiAllTime: 87.2,
    pnl1d: 36.8,
    pnl7d: 228.4,
    pnl30d: 924.5,
    maxDrawdown: -3.6,
    assets: ["BTC", "ETH"],
    activeUsers: 3892,
    description:
      "Dollar-cost averaging bot with intelligent entry timing optimization",
    winRate: 78.4,
    sharpeRatio: 3.12,
    avgDailyTrades: 2.1,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "6",
    name: "Momentum Surge",
    strategy: "Trend Following",
    riskLevel: "High",
    roi1d: 3.2,
    roi7d: 15.2,
    roi30d: 52.8,
    roiAllTime: 278.5,
    pnl1d: 168.7,
    pnl7d: 804.2,
    pnl30d: 2790.4,
    maxDrawdown: -18.3,
    assets: ["BTC", "SOL", "AVAX", "DOT"],
    activeUsers: 1124,
    description:
      "Aggressive momentum trading bot for capturing explosive market moves",
    winRate: 64.2,
    sharpeRatio: 1.76,
    avgDailyTrades: 6.3,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "7",
    name: "Volatility Hunter",
    strategy: "Scalping",
    riskLevel: "High",
    roi1d: 2.1,
    roi7d: 11.4,
    roi30d: 42.1,
    roiAllTime: 201.3,
    pnl1d: 115.6,
    pnl7d: 684.5,
    pnl30d: 2526.1,
    maxDrawdown: -16.7,
    assets: ["ETH", "BNB", "MATIC", "ATOM"],
    activeUsers: 867,
    description: "Volatility-based scalping strategy for rapid trade execution",
    winRate: 69.7,
    sharpeRatio: 1.92,
    avgDailyTrades: 15.4,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "8",
    name: "Stable Grid",
    strategy: "Grid Trading",
    riskLevel: "Low",
    roi1d: 0.5,
    roi7d: 2.9,
    roi30d: 12.8,
    roiAllTime: 71.5,
    pnl1d: 32.5,
    pnl7d: 174.2,
    pnl30d: 768.1,
    maxDrawdown: -4.2,
    assets: ["BNB", "ADA", "XRP"],
    activeUsers: 2987,
    description:
      "Conservative grid strategy focused on stable, predictable returns",
    winRate: 73.9,
    sharpeRatio: 3.45,
    avgDailyTrades: 2.8,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "9",
    name: "Quantum Arbitrage",
    strategy: "Mean Reversion",
    riskLevel: "Medium",
    roi1d: 1.4,
    roi7d: 7.8,
    roi30d: 28.4,
    roiAllTime: 142.6,
    pnl1d: 79.2,
    pnl7d: 468.3,
    pnl30d: 1704.8,
    maxDrawdown: -7.9,
    assets: ["BTC", "ETH", "UNI", "AAVE"],
    activeUsers: 1523,
    description: "Multi-exchange arbitrage bot exploiting price inefficiencies",
    winRate: 76.5,
    sharpeRatio: 2.58,
    avgDailyTrades: 8.9,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "10",
    name: "Smart DCA Plus",
    strategy: "DCA",
    riskLevel: "Low",
    roi1d: 0.7,
    roi7d: 4.5,
    roi30d: 17.2,
    roiAllTime: 93.8,
    pnl1d: 42.1,
    pnl7d: 270.3,
    pnl30d: 1032.4,
    maxDrawdown: -4.1,
    assets: ["BTC", "ETH", "BNB"],
    activeUsers: 4234,
    description:
      "Enhanced DCA with market condition analysis and dynamic allocation",
    winRate: 81.2,
    sharpeRatio: 3.34,
    avgDailyTrades: 1.9,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "11",
    name: "Breakout Detector",
    strategy: "Trend Following",
    riskLevel: "Medium",
    roi1d: 2.2,
    roi7d: 10.3,
    roi30d: 36.7,
    roiAllTime: 167.9,
    pnl1d: 121.4,
    pnl7d: 618.1,
    pnl30d: 2202.5,
    maxDrawdown: -10.5,
    assets: ["ETH", "SOL", "LINK", "DOT"],
    activeUsers: 1678,
    description:
      "Pattern recognition bot specialized in breakout trading strategies",
    winRate: 67.3,
    sharpeRatio: 2.08,
    avgDailyTrades: 4.7,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
  {
    id: "12",
    name: "Night Scalper",
    strategy: "Scalping",
    riskLevel: "High",
    roi1d: 1.8,
    roi7d: 9.6,
    roi30d: 40.2,
    roiAllTime: 195.7,
    pnl1d: 98.5,
    pnl7d: 576.4,
    pnl30d: 2412.1,
    maxDrawdown: -14.8,
    assets: ["BTC", "ETH", "BNB", "SOL"],
    activeUsers: 1045,
    description: "Optimized for low-liquidity night trading sessions",
    winRate: 71.8,
    sharpeRatio: 1.85,
    avgDailyTrades: 18.3,
    status: "healthy",
    coin: getRandomCoinSymbol(),
  },
];
